use std::collections::BTreeMap;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ScriptFlavor {
    Sh,
    PowerShell,
}

/// POSIX single-quote quoting. Everything inside `'…'` is literal, so the
/// only escape needed is for `'` itself: close the quote, emit an escaped
/// quote, reopen. Handles `$`, backticks, newlines and `"` for free.
pub fn quote_sh(s: &str) -> String {
    format!("'{}'", s.replace('\'', r"'\''"))
}

/// PowerShell single-quote quoting. Inside `'…'` no expansion occurs and a
/// literal quote is written by doubling it.
pub fn quote_ps(s: &str) -> String {
    format!("'{}'", s.replace('\'', "''"))
}

/// Session-identity markers Claude Code stamps into every process it spawns,
/// which must be cleared before starting an unrelated session.
///
/// Switchboard can itself be launched from inside a Claude Code session (a
/// `pnpm tauri dev` run started from the CLI is the common case). The whole
/// marker set is then in the app's own environment, `Command::spawn`
/// inherits it, and the terminal passes it to `claude` — which sees
/// `CLAUDE_CODE_CHILD_SESSION` and silently disables transcript saving:
///
///   ⚠ Transcript saving is off — inherited CLAUDE_CODE_CHILD_SESSION marker
///
/// A session with no transcript never appears in the Sessions tab and cannot
/// be resumed, so the feature quietly breaks itself.
///
/// The list is the union of the two sets Claude Code itself maintains: what
/// it injects into children (`CLAUDECODE`, `CLAUDE_CODE_SESSION_ID`,
/// `CLAUDE_CODE_CHILD_SESSION`, `CLAUDE_PID`, plus `AI_AGENT`,
/// `CLAUDE_EFFORT` and `TRACEPARENT` when set) and what it deletes when
/// spawning a detached session (the same four plus
/// `CLAUDE_CODE_BRIDGE_SESSION_ID` and `CLAUDE_BG_AUTH_SNAPSHOT_PATH`).
///
/// Unsetting is deliberately preferred over `CLAUDE_CODE_FORCE_SESSION_PERSISTENCE=1`,
/// which suppresses the warning while leaving the session still marked as
/// somebody else's child.
const SESSION_MARKERS: [&str; 9] = [
    "CLAUDECODE",
    "CLAUDE_CODE_SESSION_ID",
    "CLAUDE_CODE_CHILD_SESSION",
    "CLAUDE_CODE_BRIDGE_SESSION_ID",
    "CLAUDE_BG_AUTH_SNAPSHOT_PATH",
    "CLAUDE_PID",
    "CLAUDE_EFFORT",
    "AI_AGENT",
    "TRACEPARENT",
];

pub fn render(
    flavor: ScriptFlavor,
    cwd: &str,
    env: &BTreeMap<String, String>,
    claude_path: &str,
    extra_args: &[String],
    resume: Option<&str>,
) -> String {
    let q: fn(&str) -> String = match flavor {
        ScriptFlavor::Sh => quote_sh,
        ScriptFlavor::PowerShell => quote_ps,
    };

    let mut s = String::new();
    match flavor {
        ScriptFlavor::Sh => {
            s.push_str("#!/bin/sh\n# Generated by Claude Switchboard. Safe to delete.\n");
            s.push_str(&format!("cd {} || exit 1\n", q(cwd)));
            // Before the provider's own exports: this is a new session, not a
            // child of whatever process happened to start Switchboard.
            s.push_str("# Start a session of our own, not a child of this process.\n");
            for k in SESSION_MARKERS {
                s.push_str(&format!("unset {k}\n"));
            }
            for (k, v) in env {
                s.push_str(&format!("export {}={}\n", k, q(v)));
            }
            s.push_str(&format!("exec {}", q(claude_path)));
        }
        ScriptFlavor::PowerShell => {
            s.push_str("# Generated by Claude Switchboard. Safe to delete.\n");
            s.push_str(&format!("Set-Location {}\n", q(cwd)));
            s.push_str("# Start a session of our own, not a child of this process.\n");
            for k in SESSION_MARKERS {
                // Remove-Item on a non-existent Env: entry is an error, so
                // -ErrorAction SilentlyContinue is required, not decorative.
                s.push_str(&format!(
                    "Remove-Item Env:\\{k} -ErrorAction SilentlyContinue\n"
                ));
            }
            for (k, v) in env {
                s.push_str(&format!("$env:{} = {}\n", k, q(v)));
            }
            s.push_str(&format!("& {}", q(claude_path)));
        }
    }

    // Provider-supplied flags, each quoted individually — never joined into a
    // single string, which would make one argument out of several.
    for a in extra_args {
        s.push(' ');
        s.push_str(&q(a));
    }

    // `--fork-session` is not optional (Spec B §7.1): resuming a session that
    // is still open elsewhere would otherwise put two Claude Code processes on
    // the same transcript file, corrupting history that cannot be rebuilt.
    if let Some(id) = resume {
        s.push_str(&format!(" --resume {} --fork-session", q(id)));
    }

    s.push('\n');
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    #[cfg(unix)]
    use tempfile::tempdir;

    fn env() -> BTreeMap<String, String> {
        BTreeMap::from([
            (
                "ANTHROPIC_BASE_URL".to_string(),
                "https://api.z.ai/api/anthropic".to_string(),
            ),
            ("ANTHROPIC_MODEL".to_string(), "glm-5.2".to_string()),
        ])
    }

    #[test]
    fn sh_quoting_neutralizes_single_quotes() {
        assert_eq!(quote_sh("ab'cd"), r"'ab'\''cd'");
    }

    #[test]
    fn sh_quoting_leaves_shell_metacharacters_inert() {
        let q = quote_sh("$(rm -rf /) `whoami` \"x\" ; echo pwned");
        assert!(q.starts_with('\'') && q.ends_with('\''));
        assert!(!q.contains(r"'\''"), "no quote-breaks expected in this input");
    }

    #[test]
    fn ps_quoting_doubles_single_quotes() {
        assert_eq!(quote_ps("ab'cd"), "'ab''cd'");
    }

    #[test]
    fn sh_script_has_shebang_cd_exports_and_exec() {
        let s = render(
            ScriptFlavor::Sh,
            "/tmp/my project",
            &env(),
            "/opt/homebrew/bin/claude",
            &[],
            None,
        );
        assert!(s.starts_with("#!/bin/sh\n"));
        assert!(s.contains("cd '/tmp/my project' || exit 1"));
        assert!(s.contains("export ANTHROPIC_MODEL='glm-5.2'"));
        assert!(s.trim_end().ends_with("exec '/opt/homebrew/bin/claude'"));
    }

    #[test]
    fn sh_script_appends_resume_flag() {
        let s = render(
            ScriptFlavor::Sh,
            "/tmp",
            &env(),
            "/usr/bin/claude",
            &[],
            Some("57ca2089-1111"),
        );
        assert!(s
            .trim_end()
            .ends_with("exec '/usr/bin/claude' --resume '57ca2089-1111' --fork-session"));
    }

    #[test]
    fn ps_script_sets_env_and_invokes_claude() {
        let s = render(
            ScriptFlavor::PowerShell,
            r"C:\Users\me\my project",
            &env(),
            r"C:\Program Files\claude.exe",
            &[],
            None,
        );
        assert!(s.contains(r"Set-Location 'C:\Users\me\my project'"));
        assert!(s.contains("$env:ANTHROPIC_MODEL = 'glm-5.2'"));
        assert!(s.trim_end().ends_with(r"& 'C:\Program Files\claude.exe'"));
    }

    /// Switchboard is often started from inside a Claude Code session, so its
    /// own environment carries that session's identity markers. Passing them
    /// through makes `claude` treat the new session as a child and disable
    /// transcript saving entirely — the session then never appears in the
    /// Sessions tab and cannot be resumed. It fails with a one-line warning,
    /// not an error, which is exactly the kind of thing a test has to catch.
    #[test]
    fn sh_script_clears_inherited_session_markers_before_exporting() {
        let s = render(
            ScriptFlavor::Sh,
            "/tmp",
            &env(),
            "/usr/bin/claude",
            &[],
            None,
        );
        for k in SESSION_MARKERS {
            assert!(
                s.contains(&format!("unset {k}\n")),
                "{k} must be unset; leaving it disables transcript saving"
            );
        }
        // Ordering matters: an unset after the provider's exports would undo
        // them if the two sets ever overlapped.
        let unset_at = s.rfind("unset ").expect("unsets present");
        let export_at = s.find("export ANTHROPIC_").expect("exports present");
        assert!(unset_at < export_at, "unsets must precede exports:\n{s}");
    }

    #[test]
    fn ps_script_clears_inherited_session_markers_before_assigning() {
        let s = render(
            ScriptFlavor::PowerShell,
            r"C:\work",
            &env(),
            r"C:\claude.exe",
            &[],
            None,
        );
        for k in SESSION_MARKERS {
            assert!(
                s.contains(&format!("Remove-Item Env:\\{k} -ErrorAction SilentlyContinue\n")),
                "{k} must be removed, and silently — Remove-Item errors on a missing entry"
            );
        }
        let remove_at = s.rfind("Remove-Item ").expect("removals present");
        let assign_at = s.find("$env:ANTHROPIC_").expect("assignments present");
        assert!(remove_at < assign_at, "removals must precede assignments:\n{s}");
    }

    /// The generated script must actually clear the markers when run, not
    /// merely contain the right text.
    #[cfg(unix)]
    #[test]
    fn a_launched_session_does_not_inherit_a_child_session_marker() {
        let d = tempdir().unwrap();
        let s = render(
            ScriptFlavor::Sh,
            "/tmp",
            &env(),
            "/bin/sh",
            &[
                "-c".to_string(),
                "printf '[%s][%s]' \"$CLAUDE_CODE_CHILD_SESSION\" \"$CLAUDECODE\"".to_string(),
            ],
            None,
        );
        let script = d.path().join("t.sh");
        std::fs::write(&script, &s).unwrap();

        let out = std::process::Command::new("/bin/sh")
            .arg(&script)
            // Exactly the situation this guards: the parent is a Claude Code
            // session, so the markers are live in the inherited environment.
            .env("CLAUDE_CODE_CHILD_SESSION", "1")
            .env("CLAUDECODE", "1")
            .env("CLAUDE_CODE_SESSION_ID", "029a3e04-fa36")
            .output()
            .expect("run generated script");
        assert_eq!(
            String::from_utf8_lossy(&out.stdout),
            "[][]",
            "markers leaked into the launched session:\n{s}"
        );
    }

    #[test]
    fn injection_attempt_in_token_stays_inside_the_string() {
        let mut e = env();
        e.insert(
            "ANTHROPIC_AUTH_TOKEN".to_string(),
            "x'; rm -rf ~; echo '".to_string(),
        );
        let s = render(ScriptFlavor::Sh, "/tmp", &e, "/usr/bin/claude", &[], None);
        // The dangerous text must appear only inside a quoted export line.
        let line = s
            .lines()
            .find(|l| l.starts_with("export ANTHROPIC_AUTH_TOKEN="))
            .unwrap();
        assert_eq!(
            line,
            r"export ANTHROPIC_AUTH_TOKEN='x'\''; rm -rf ~; echo '\'''"
        );
        assert!(!s.contains("\nrm -rf"), "payload must never start its own line");
    }

    /// Spec §3.1 — a newline in any interpolated value must not be able to
    /// become a live command. The header comment is a fixed string, so a
    /// provider name cannot reach the script at all; this guards the values
    /// that do.
    ///
    /// Asserted by *executing* the rendered script rather than by scanning it
    /// for textual line starts. POSIX single-quoting deliberately lets a value
    /// span textual lines — `export X='a⏎rm -rf y⏎#'` is one word to `/bin/sh`
    /// and the `rm` never runs. A line-start scan would therefore fail on
    /// correct output while proving nothing about what the shell does; only
    /// running it settles the question.
    #[cfg(unix)]
    #[test]
    fn newlines_in_values_cannot_introduce_a_script_line() {
        let d = tempdir().unwrap();
        let canary = d.path().join("CANARY");
        std::fs::write(&canary, "x").unwrap();
        let payload = format!("glm\nrm -f {}\n#", canary.display());

        let mut e = env();
        e.insert("ANTHROPIC_MODEL".to_string(), payload.clone());
        // `true` stands in for the claude binary so the script terminates.
        let s = render(ScriptFlavor::Sh, "/tmp", &e, "/usr/bin/true", &[], None);

        let script = d.path().join("t.sh");
        std::fs::write(&script, &s).unwrap();
        let out = std::process::Command::new("/bin/sh")
            .arg(&script)
            .output()
            .expect("run generated script");
        assert!(out.status.success(), "generated script must be valid sh: {s}");
        assert!(
            canary.exists(),
            "the newline payload executed as a command — quoting failed:\n{s}"
        );

        // And the value survives intact rather than being truncated at the
        // newline, which would silently misconfigure the session.
        let echo = render(
            ScriptFlavor::Sh,
            "/tmp",
            &e,
            "/bin/sh",
            &["-c".to_string(), "printf %s \"$ANTHROPIC_MODEL\"".to_string()],
            None,
        );
        let script2 = d.path().join("t2.sh");
        std::fs::write(&script2, &echo).unwrap();
        let out2 = std::process::Command::new("/bin/sh")
            .arg(&script2)
            .output()
            .expect("run generated script");
        assert_eq!(String::from_utf8_lossy(&out2.stdout), payload);

        // Same for the working directory: a newline in `cwd` must not escape
        // its quoting either.
        let canary2 = d.path().join("CANARY2");
        std::fs::write(&canary2, "x").unwrap();
        let s2 = render(
            ScriptFlavor::Sh,
            &format!("/tmp\nrm -f {}\n", canary2.display()),
            &env(),
            "/usr/bin/true",
            &[],
            None,
        );
        let script3 = d.path().join("t3.sh");
        std::fs::write(&script3, &s2).unwrap();
        // `cd` to a bogus path exits 1 by design; what matters is that the
        // payload did not run as its own command.
        let _ = std::process::Command::new("/bin/sh").arg(&script3).output();
        assert!(canary2.exists(), "cwd escaped its quoting:\n{s2}");
    }

    #[test]
    fn generated_script_never_interpolates_a_provider_name() {
        let s = render(ScriptFlavor::Sh, "/tmp", &env(), "/usr/bin/claude", &[], None);
        assert!(
            s.contains("# Generated by Claude Switchboard. Safe to delete."),
            "header must be a fixed string, not built from provider data"
        );
    }

    /// The generated script execs the binary directly, bypassing any shell
    /// `claude()` wrapper — so flags the user relies on must be reproduced.
    #[test]
    fn extra_args_are_appended_and_quoted_individually() {
        let args = vec![
            "--dangerously-skip-permissions".to_string(),
            "--append-system-prompt".to_string(),
            "be terse; don't stop".to_string(),
        ];
        let s = render(ScriptFlavor::Sh, "/tmp", &env(), "/usr/bin/claude", &args, None);
        assert!(
            s.trim_end().ends_with(
                "exec '/usr/bin/claude' '--dangerously-skip-permissions' '--append-system-prompt' 'be terse; don'\\''t stop'"
            ),
            "got: {}",
            s.trim_end()
        );
    }

    #[test]
    fn resume_always_forks_the_session() {
        let s = render(
            ScriptFlavor::Sh,
            "/tmp",
            &env(),
            "/usr/bin/claude",
            &[],
            Some("abc-123"),
        );
        assert!(
            s.contains("--fork-session"),
            "resuming without --fork-session lets two processes share one transcript"
        );
        let ps = render(
            ScriptFlavor::PowerShell,
            "C:\\w",
            &env(),
            "claude.exe",
            &[],
            Some("abc-123"),
        );
        assert!(ps.contains("--fork-session"), "PowerShell path must fork too");
    }

    #[test]
    fn no_fork_flag_when_not_resuming() {
        let s = render(ScriptFlavor::Sh, "/tmp", &env(), "/usr/bin/claude", &[], None);
        assert!(!s.contains("--fork-session"));
        assert!(!s.contains("--resume"));
    }

    #[test]
    fn env_order_is_deterministic() {
        let a = render(ScriptFlavor::Sh, "/tmp", &env(), "/usr/bin/claude", &[], None);
        let b = render(ScriptFlavor::Sh, "/tmp", &env(), "/usr/bin/claude", &[], None);
        assert_eq!(a, b);
    }
}
